// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEw2i8RfIeeXlPZY9_pu7D9rlk58L8RZg',
    appId: '1:351331152013:web:b39cef86c7335aa5e1b2c4',
    messagingSenderId: '351331152013',
    projectId: 'smart-finsight',
    authDomain: 'smart-finsight.firebaseapp.com',
    storageBucket: 'smart-finsight.firebasestorage.app',
    measurementId: 'G-9JTW5263W6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMP1ACcAZ8lxzKQp1D4N3fp1w4HIwcpwA',
    appId: '1:351331152013:android:2fbedc02620f3ea3e1b2c4',
    messagingSenderId: '351331152013',
    projectId: 'smart-finsight',
    storageBucket: 'smart-finsight.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuPynl95i5Gv1c6LY8srQBhW8_GVJo1xU',
    appId: '1:351331152013:ios:054ac02add555d8de1b2c4',
    messagingSenderId: '351331152013',
    projectId: 'smart-finsight',
    storageBucket: 'smart-finsight.firebasestorage.app',
    iosBundleId: 'com.example.smartFinsight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuPynl95i5Gv1c6LY8srQBhW8_GVJo1xU',
    appId: '1:351331152013:ios:054ac02add555d8de1b2c4',
    messagingSenderId: '351331152013',
    projectId: 'smart-finsight',
    storageBucket: 'smart-finsight.firebasestorage.app',
    iosBundleId: 'com.example.smartFinsight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEw2i8RfIeeXlPZY9_pu7D9rlk58L8RZg',
    appId: '1:351331152013:web:553819bdef248e0fe1b2c4',
    messagingSenderId: '351331152013',
    projectId: 'smart-finsight',
    authDomain: 'smart-finsight.firebaseapp.com',
    storageBucket: 'smart-finsight.firebasestorage.app',
    measurementId: 'G-NF6YNY1P4Q',
  );
}
